
if (GetLocale() =="zhCN") then
	SPELL_TIMER_TITLE = "法术计时器";
	SPELL_TIMER_TEXT_OPTION_SLIDER = "你可以在原有法术的持续时间上再额外增加一段时间，拖动该滑动条来调整该时间。";
	SPELL_TIMER_SHOW_NAME = "显示魔法名称";
	SPELL_TIMER_SHOW_PROGRESS = "显示进度条";

	SPELL_TIMER_POISON = "药膏";
	SPELL_TIMER_VENOMOUS = "毒蛇";

	SPELL_TIMER_TRAP_PATTERN1 = "(.-)效果";
	SPELL_TIMER_TRAP_PATTERN2 = "(.-)光环";

	SPELL_TIMER_TOTEM_PATTERN = "图腾";

	SPELL_TIMER_TOTEM_TIP = "你可以使用鼠标右键取消该图腾。"

	SPELL_TIMER_UNITFRAME_TOOLTIP = "点击小锁解开/锁定窗口";

	SPELLTIMER_HOUR_WORD = "小时";
	SPELLTIMER_MINUTE_WORD = "分钟";
	SPELLTIMER_SECOND_WORD = "秒";

	SPELLTIMER_COOLDOWN_INFO = "%s的剩余时间还有%s。";

	SPELL_TIMER_PATTERN_TABLE = {};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"] = {};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恐惧"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["献祭"] = {"debuff", {"痛苦无常"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["放逐术"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["腐蚀术"] = {"debuff", {"腐蚀之种"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["腐蚀之种"] = {"debuff", {"腐蚀术"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["末日灾祸"] = {"debuff", {"痛苦灾祸","浩劫灾祸"},{["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["浩劫灾祸"] = {"debuff", {"末日灾祸","痛苦灾祸"},{["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["痛苦灾祸"] = {"debuff", {"末日灾祸","浩劫灾祸"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["元素诅咒"] = {"debuff", {"虚弱诅咒", "语言诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["虚弱诅咒"] = {"debuff", {"元素诅咒", "语言诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["语言诅咒"] = {"debuff", {"元素诅咒", "虚弱诅咒", "疲劳诅咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["疲劳诅咒"] = {"debuff", {"元素诅咒", "虚弱诅咒", "语言诅咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["死亡缠绕"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恐惧嚎叫"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["暗影烈焰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["奴役恶魔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["痛苦无常"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["鬼影缠身"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恶魔之魂"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["暗影防护结界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["虚空结界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恶魔变形"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恶魔重生"] = {"buff", nil, {["live"] = 1, ["spell"] = {"恶魔重生 CD", 120}}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["挑战嚎叫"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["暗影之怒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["古尔丹之手"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["厄兆光环"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["诱惑"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["法术封锁"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["巨斧投掷"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["军团打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["痛楚"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["末日降临"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["ROGUE"] = {};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"][SPELL_TIMER_POISON] = {};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["凿击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["锁喉"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["闷棍"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["破甲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["偷袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["致盲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["毒伤"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["恢复"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["切割"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["脚踢"] = {"持续%t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["扰乱"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["肾击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["仇杀"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["暗影之舞"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["洞悉弱点"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["冲动"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["消失"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["烟雾弹"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["佯攻"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["嫁祸诀窍"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["疾跑"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["闪避"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["暗影步"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["装死"] = {"buff", nil, {["live"] = 1, ["spell"] = {"装死 CD", 90}}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["出血"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["暗影斗篷"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["备战就绪"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["要害打击"] = {"debuff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["致命投掷"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["拆卸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["打劫"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["铁棍"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["PRIEST"] = {};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["暗言术：痛"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["沉默"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["麻痹"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["心灵尖啸"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["吸血鬼之触"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["心灵惊骇"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["束缚亡灵"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["妙手回春"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["噬灵疫病"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["神圣之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["安抚心灵"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["暗影恶魔"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["摧心魔"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["真言术：盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["愈合祷言"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["恢复"] = {"buff", nil, {["live"] = 1,["needMana"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["守护之魂"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["能量灌注"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["真言术：障"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["灵魂之力"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["痛苦压制"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["消散"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["渐隐术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["祈福"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["圣言术：静"] = {"buff", nil, {["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["WARRIOR"] = {};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["断筋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["强化断筋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["撕裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["挫志怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["刺耳怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["雷霆一击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["巨人打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["缴械"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["破胆怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["破甲攻击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["致死打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["碎裂投掷"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["击倒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["拦截"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["挑战怒吼"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["法术反射"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["怒火中烧"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["致命平静"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["横扫攻击"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["剑刃风暴"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["嗜血"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["狂暴之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["狂怒回复"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["死亡之愿"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["破釜沉舟"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["反击风暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["盾墙"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["鲁莽"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["震荡猛击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["震荡波"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["HUNTER"] = {};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["照明弹"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["摔绊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["恐吓野兽"] = {"debuff",nil,{["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["猎人印记"] = {"debuff",nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["反击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["治疗宠物"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["野兽之心"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["主人的召唤"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毒蛇钉刺"] = {"debuff", {"翼龙钉刺"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["翼龙钉刺"] = {"debuff", {"毒蛇钉刺"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["冰冻陷阱"] = {{"SpellTimer_TrapSearchFunc", {"最多%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["冰霜陷阱"] = {{"SpellTimer_TrapSearchFunc", {"持续%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["献祭陷阱"] = {{"SpellTimer_TrapSearchFunc", {"在%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["爆炸陷阱"] = {{"SpellTimer_TrapSearchFunc", {"接下来的%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毒蛇陷阱"] = {{"SpellTimer_TrapSearchFunc", {"将在%t", "存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["威慑"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["集中火力"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["急速射击"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["震荡射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["沉默射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["死亡标记"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["胁迫"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["驱散射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["蜘蛛毒刺"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["扰乱射击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["黑箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毒性喷网"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["钉身"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["挫志咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["挫志尖啸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["冰霜吐息"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["夺械"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["腐蚀唾液"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毁灭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["火焰吐息"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["巨兽撕咬"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["裂甲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["蛮兽打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["钳取"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["熔岩吐息"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["闪电吐息"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["蛛网"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["酸液喷吐"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["碎踝"] = {"debuff"};
	--SPELL_TIMER_PATTERN_TABLE["HUNTER"]["突奔"] = {"debuff"};
	--SPELL_TIMER_PATTERN_TABLE["HUNTER"]["撞击"] = {"debuff"};
	--SPELL_TIMER_PATTERN_TABLE["HUNTER"]["裂筋"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["DRUID"] = {};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["休眠"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["月火术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["猛击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["挫志咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["精灵之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["精灵之火（野性）"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["纠缠根须"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["突袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["感染伤口"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["愈合"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["回春术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["粉碎"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["斜掠"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["野性冲锋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["虫群"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["自然之力"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["裂伤"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["割伤"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["日光术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["阳炎术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["生命绽放"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["割碎"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["野蛮咆哮"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["野性成长"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["台风"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["星辰坠落"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["自然之握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["旋风"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["树皮术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["激活"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["猛虎之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["急奔"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["荆棘术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["狂暴回复"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["狂奔怒吼"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["激怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["生存本能"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["狂暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["生命之树"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["挑战咆哮"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["痛击"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["SHAMAN"] = {};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["风暴打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["元素掌握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["漩涡武器"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["激流"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["萨满之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["灵魂行者的恩赐"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["烈焰震击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["束缚元素"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["冰霜之力"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["冰霜震击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["大地震击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["妖术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["野性狼魂"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["嗜血"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["英勇"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["自然的守护者"] = {"buff", nil, {["live"] = 1, ["spell"] = {"自然的守护者 CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE["PALADIN"] = {};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["制裁之锤"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["忏悔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["谴罚"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["超度邪恶"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["奉献"] = {"在%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["荣耀圣令"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["圣光道标"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["圣洁护盾"] = {"buff", nil, {["live"] = 1,["spell"] = {"圣洁护盾 CD", 60}}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["复仇之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["炽热防御者"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神圣之盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["牺牲之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["光环掌握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["狂热"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["保护之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["光辉治疗"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["异端裁决"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神圣恳求"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["圣盾术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["圣光普照"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["圣佑术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["拯救之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["自由之手"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神恩术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神圣守卫"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["审判"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["辩护"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神圣愤怒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["复仇者之盾"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["MAGE"] = {};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["变形术"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["减速"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰锥术"] = {"debuff", {"寒冰箭"}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["寒冰箭"] = {"debuff", {"冰锥术"}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["炎爆术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["炎爆术!"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["临界炽焰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["火球术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冲击波"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰霜新星"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰霜之环"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["活动炸弹"] = {"debuff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["奥术冲击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["寒冰护体"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["镜像"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["霜火之箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["强化法术反制"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["深度冻结"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["龙息术"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["法师结界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["法力护盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["隐形术"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["奥术强化"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰冷血脉"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["寒冰屏障"] = {"buff", nil, {["live"] = 1, ["spell"] = {"低温", 30}}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["灸灼"] = {"debuff", nil, {["live"] = 1, ["spell"] = {"灸灼 CD", 60}}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["减速术"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["虚空风暴"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"] = {};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰霜疫病"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["血之疫病"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["血红热疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["黑色热疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["枯萎凋零"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["绞袭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冻疮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰冷触摸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["死疽打击"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰封之韧"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["吸血鬼之血"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["巫妖之躯"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["白骨之盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰霜之柱"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["邪恶狂热"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["寒冰锁链"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["黑暗模拟"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["邪恶虫群"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["饥饿之寒"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["反魔法护罩"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["召唤石像鬼"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["反魔法领域"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["大墓地的意志"] = {"buff", nil, {["live"] = 1, ["spell"] = {"大墓地的意志 CD", 45}}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["符文刃舞"] = {"持续%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["亡者大军"] = {"buff", nil, {["live"] = 1, ["spell"] = {"食尸鬼军团", 45}}};

	SPELL_TIMER_PATTERN_TABLE["MONK"]={};
	SPELL_TIMER_PATTERN_TABLE["DEMONHUNTER"]={};

elseif (GetLocale() == "zhTW") then
	SPELL_TIMER_TITLE = "法術計時器";
	SPELL_TIMER_TEXT_OPTION_SLIDER = "你可以在原有的法術的持續時間上再額外增加一段時間，拖動滑動塊來調整該時間。";
	SPELL_TIMER_SHOW_NAME = "顯示魔法名稱";
	SPELL_TIMER_SHOW_PROGRESS = "顯示進度條";

	SPELL_TIMER_POISON = "毒藥";
	SPELL_TIMER_VENOMOUS = "毒蛇";

	SPELL_TIMER_TRAP_PATTERN1 = "(.-)效果";
	SPELL_TIMER_TRAP_PATTERN2 = "(.-)光環";

	SPELL_TIMER_TOTEM_PATTERN = "圖騰";

	SPELL_TIMER_TOTEM_TIP = "你可以使用滑鼠右鍵取消該圖騰。";

	SPELL_TIMER_UNITFRAME_TOOLTIP = "點擊小鎖解開/鎖定窗口";

	SPELLTIMER_HOUR_WORD = "小時";
	SPELLTIMER_MINUTE_WORD = "分鐘";
	SPELLTIMER_SECOND_WORD = "秒";

	SPELLTIMER_COOLDOWN_INFO = "%s的剩餘時間還有%s。";

	SPELL_TIMER_PATTERN_TABLE = {};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"] = {};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恐懼術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["獻祭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["放逐術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["腐蝕術"] = {"debuff", {"腐蝕種子"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["腐蝕種子"] = {"debuff", {"腐蝕術"}, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["末日災厄"] = {"debuff", {"痛苦災厄", "浩劫災厄"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["痛苦災厄"] = {"debuff", {"末日災厄", "浩劫災厄"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["浩劫災厄"] = {"debuff", {"末日災厄", "痛苦災厄"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["元素詛咒"] = {"debuff", { "虛弱詛咒", "語言詛咒", "疲勞詛咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["虛弱詛咒"] = {"debuff", { "元素詛咒", "語言詛咒", "疲勞詛咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["語言詛咒"] = {"debuff", { "元素詛咒", "虛弱詛咒", "疲勞詛咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["疲勞詛咒"] = {"debuff", { "元素詛咒", "虛弱詛咒", "語言詛咒"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["死亡纏繞"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["恐懼嚎叫"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["古爾丹之手"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["誘惑"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["惡魔化身"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["奴役惡魔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["痛苦動盪"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["蝕魂術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["防護暗影結界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["暗影之焰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["暗影之怒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["痛苦"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["ROGUE"] = {};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"][SPELL_TIMER_POISON] = {};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["鑿擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["絞喉"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["悶棍"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["破甲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["偷襲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["致盲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["揭底之擊"] = {"debuff"};--BUFF OR DEBUFF
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["卸除武裝"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["擲殺"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["毒化"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["切割"] = {"buff" , nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["疾跑"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["閃避"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["能量刺激"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["佯攻"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["養精蓄銳"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["戰鬥就緒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["暗影披風"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["消失"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["煙霧彈"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["偷天換日"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["死亡謊言"] = {"buff", nil, {["live"] = 1, ["spell"] = {"死亡謊言 CD", 60}}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["腳踢"] = {"持續%t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["擾亂"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["還擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["腎擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["出血"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["鮮血渴求"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["暗影之舞"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["宿怨"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["PRIEST"] = {};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["暗言術:痛"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["沉默"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["心靈尖嘯"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["恢復"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["聖言術:寧"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["漸隱術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["痛苦鎮壓"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["恩典"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["真言術:壁"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["注入能量"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["佈道"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["大天使"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["心靈烙印"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["暗影惡魔"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["癒合禱言"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["守護聖靈"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["真言術:盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["影散"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["束縛不死生物"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["噬靈瘟疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["神聖之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["安撫心靈"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["心靈恐慌"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["吸血之觸"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["星辰裂片"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["WARRIOR"] = {};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["斷筋"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["撕裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["盾擊"] = {"持續%t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["挫志怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["刺耳怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["懲戒痛擊"] = {"debuff"};--是否还存在
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["雷霆一擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["繳械"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["破膽怒吼"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["破甲攻擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["致死打擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["碎甲投擲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["挑戰怒吼"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["撂倒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["震盪猛擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["攔截"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["震懾波"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["反擊風暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["巨像碎擊"] = {"debuff"};--buff or debuff
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["狂暴之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["破釜沉舟"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["狂怒恢復"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["橫掃攻擊"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["劍下亡魂"] = {"buff", nil, {["live"] = 1, ["spell"] = {"劍下亡魂 CD", 120}}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["魯莽"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["沈著殺機"] = {"buff", {"心靈之怒"}, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["心靈之怒"] = {"buff", {"沈著殺機"}, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["死亡之願"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["盾牌格擋"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["削骨斬肉"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["盾牆"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["法術反射"] = {"buff", nil, {["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["HUNTER"] = {};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["照明彈"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["摔絆"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["恐嚇野獸"] = {"debuff",nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["反擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["寡婦毒液"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["治療寵物"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["狂野怒火"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["專注之火"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["威懾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["主人的呼喚"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["急速射擊"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["沉默射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["獵人印記"] = {"debuff",nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["死亡標記"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["擾亂射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毒蛇釘刺"] = {"debuff", {"蝮蛇釘刺", "毒蠍釘刺", "翼龍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["蝮蛇釘刺"] = {"debuff", {"毒蛇釘刺", "毒蠍釘刺", "翼龍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毒蠍釘刺"] = {"debuff", {"毒蛇釘刺", "蝮蛇釘刺", "翼龍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["翼龍釘刺"] = {"debuff", {"毒蛇釘刺", "蝮蛇釘刺", "毒蠍釘刺"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["震盪射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["驅散射擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["黑蝕箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["冰凍陷阱"] = {{"SpellTimer_TrapSearchFunc", {"最多%t內", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["冰霜陷阱"] = {{"SpellTimer_TrapSearchFunc", {"持續%t", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["獻祭陷阱"] = {{"SpellTimer_TrapSearchFunc", {"在%t內", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["爆炸陷阱"] = {{"SpellTimer_TrapSearchFunc", {"接下來的%t", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["毒蛇陷阱"] = {{"SpellTimer_TrapSearchFunc", {"毒蛇將在%t", "陷阱可存在%t"}, "SpellTimer_TrapActiveFunc"}, nil, {["live"] = 1,["notarget"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["DRUID"] = {};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["休眠"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["月火術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["重擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["挫志咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["精靈之火"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["精靈之火(野性)"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["啟動"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["奔竄咆哮"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["樹皮術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["糾纏根鬚"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["突襲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["血襲"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["撕扯"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["感染之傷"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["挑戰咆哮"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["狂暴恢復"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["自然之握"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["荊棘術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["癒合"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["回春術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["狂暴"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["求生本能"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["掃擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["野性衝鋒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["蟲群"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["自然之力"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["割碎"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["割裂"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["狂怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["生命之花"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["星殞術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["傷殘術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["突進"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["日炎術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["痛擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["颱風"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["奔竄"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["野性痊癒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["自然之賜"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["兇蠻咆哮"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["颶風術"] = {"debuff", nil, {["unique"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["SHAMAN"] = {};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["風暴打擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["靈行者之賜"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["精通元素"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["薩滿之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["氣漩武器"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["激流"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["烈焰震擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["冰霜震擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["地縛圖騰"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["妖術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["大地震擊"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["野性之魂"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["元素束縛"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["嗜血術"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["英勇氣概"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["自然守護者"] = {"buff", nil, {["live"] = 1, ["spell"] = {"自然守護者 CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE["PALADIN"] = {};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["制裁之錘"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["懺悔"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["退邪術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["自由聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["拯救聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["異端審問"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["犧牲聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["保護聖禦"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神聖啟發"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["光明賜福"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["復仇之怒"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神性祈求"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["聖盾術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["聖佑術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["精通光環"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神恩術"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["狂熱精神"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["忠誠防衛者"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["聖光信標"] = {"buff", nil, {["live"] = 1,["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["公正復仇"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神聖憤怒"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["神性守護"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["遠古諸王守護者"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["MAGE"] = {};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["變形術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰錐術"] = {"debuff", {"寒冰箭"}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["寒冰箭"] = {"debuff", {"冰錐術"}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["炎爆術"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["霜火箭"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["烈燄之球"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["寒冰屏障"] = {"buff", nil, {["live"] = 1, ["spell"] = {"低温", 30}}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["法力護盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["法師結界"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["幻鏡之像"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["秘法衝擊"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰寒脈動"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["寒冰護體"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["秘法強化"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["衝擊波"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["龍之吐息"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["冰霜新星"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["減速術"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["極度冰凍"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["活體爆彈"] = {"debuff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["燃火"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"] = {};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰錮堅韌"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["反魔法護罩"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["骸骨之盾"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["血族之裔"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰霜之柱"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["巫妖之軀"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["邪惡狂熱"] = {"buff", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰霜熱疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["血魄瘟疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["黑死瘟疫"] = {"debuff", nil, {["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["噬溫酷寒"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["絞殺"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["亡域打擊"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["反魔法力場"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["召喚石像鬼"] = {"持續%t", nil, {["live"] = 1,["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["死亡之握"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["黑暗幻象"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰結之觸"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["穢邪荒疫"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["冰鍊術"]   = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["亡域意志"] = {"buff", nil, {["live"] = 1, ["spell"] = {"亡域意志 CD", 45}}};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["亡靈大軍"] = {"buff", nil, {["live"] = 1, ["spell"] = {"亡靈军团", 45}}};

	SPELL_TIMER_PATTERN_TABLE["MONK"]={};
	SPELL_TIMER_PATTERN_TABLE["DEMONHUNTER"]={};
else
	SPELL_TIMER_TITLE = "SpellTimer";
	SPELL_TIMER_TEXT_OPTION_SLIDER = "You can add some time on this spell .";
	SPELL_TIMER_SHOW_NAME = "Show spell name";
	SPELL_TIMER_SHOW_PROGRESS = "Show Progress bar";

	SPELL_TIMER_POISON = "Poison";

	SPELL_TIMER_TRAP_PATTERN1 = "(.-) effect";
	SPELL_TIMER_TRAP_PATTERN2 = "(.-) aura$";

	SPELL_TIMER_TOTEM_PATTERN = "Totem";

	SPELL_TIMER_TOTEM_TIP = "Right click to cancel totem.";

	SPELL_TIMER_UNITFRAME_TOOLTIP = "Click the lock unlock/lock the window";

	SPELLTIMER_HOUR_WORD = " hour";
	SPELLTIMER_MINUTE_WORD = " min";
	SPELLTIMER_SECOND_WORD = " sec";

	SPELLTIMER_COOLDOWN_INFO = "%s remains %s.";

	SPELL_TIMER_PATTERN_TABLE = {};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"] = {};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Fear"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Immolate"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Banish"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Corruption"] = {"debuff", {"Seed of Corruption"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Seed of Corruption"] = {"over %t", {"Corruption"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Siphon Life"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Doom"] = {"after %t", {"Curse of Agony", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Agony"] = {"over %t", {"Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of the Elements"] = {"target for %t", {"Curse of Agony", "Curse of Doom", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Weakness"] = {"for %t.", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Tongues"] = {"Lasts %t.", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Recklessness", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Recklessness"] = {"for %t.", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Shado", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Shadow"] = {"for %t", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Exhaustion"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Curse of Exhaustion"] = {"for %t", {"Curse of Agony", "Curse of Doom", "Curse of the Elements", "Curse of Weakness", "Curse of Tongues", "Curse of Recklessness", "Curse of Shado"}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Death Coil"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Howl of Terror"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Enslave Demon"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Unstable Affliction"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARLOCK"]["Haunt"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["ROGUE"] = {};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"][SPELL_TIMER_POISON] = {};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Gouge"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Garrote"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Sap"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Expose Armor"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Cheap Shot"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Blind"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Rupture"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Slice and Dice"] = {"buff", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Kick"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Distract"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Riposte"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Kidney Shot"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Hunger For Blood"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["ROGUE"]["Shadow Dance"] = {"buff"};

	SPELL_TIMER_PATTERN_TABLE["PRIEST"] = {};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Shadow Word: Pain"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Silence"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Psychic Scream"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Vampiric Embrace"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Renew"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Shackle Undead"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Devouring Plague"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Mind Control"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Holy Fire"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Mind Soothe"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Vampiric Touch"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["PRIEST"]["Starshards"] = {"over %t"};

	SPELL_TIMER_PATTERN_TABLE["WARRIOR"] = {};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Hamstring"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Rend"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Shield Bash"] = {"cast for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Demoralizing Shout"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Piercing Howl"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Mocking Blow"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Thunder Clap"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Disarm"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Intimidating Shout"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Sunder Armor"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Mortal Strike"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Intercept"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["WARRIOR"]["Rampage"] = {"Lasts %t", nil, {["notarget"] = 1, ["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["HUNTER"] = {};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Flare"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Wing Clip"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Scare Beast"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Counterattack"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Mend Pet"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Bestial Wrath"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Serpent Sting"] = {"debuff", {"Viper Sting", "Scorpid Sting", "Wyvern Sting"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Viper Sting"] = {"debuff", {"Serpent Sting", "Scorpid Sting", "Wyvern Sting"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Scorpid Sting"] = {"debuff", {"Serpent Sting", "Viper Sting", "Wyvern Sting"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Wyvern Sting"] = {"debuff", {"Serpent Sting", "Viper Sting", "Scorpid Sting"}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Concussive Shot"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Scatter Shot"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Freezing Trap"] = {{"SpellTimer_TrapSearchFunc", {"preventing all action for up to %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, nil, nil, {"Frost Trap", "Immolation Tra", "Explosive Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Frost Trap"] = {{"SpellTimer_TrapSearchFunc", {"around itself for %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Immolation Trap", "Explosive Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Immolation Trap"] = {{"SpellTimer_TrapSearchFunc", {"damage over %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Frost Trap", "Explosive Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Explosive Trap"] = {{"SpellTimer_TrapSearchFunc", {"damage over %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Frost Trap", "Immolation Trap", "Snake Trap"}, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["HUNTER"]["Snake Trap"] = {{"SpellTimer_TrapSearchFunc", {"after %t", "exist for %t"}, "SpellTimer_TrapActiveFunc"}, {"Freezing Trap", "Frost Trap", "Immolation Trap", "Explosive Trap"}, {["notarget"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["DRUID"] = {};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Hibernate"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Moonfire"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Bash"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Demoralizing Roar"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Faerie Fire"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Faerie Fire"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Entangling Roots"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Pounce"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Pounce Bleed"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Rip"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Regrowth"] = {"over %t", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Rejuvenation"] = {"over %t", nil, {["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Rake"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Feral Charge"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Insect Swarm"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Bash"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Force of Nature"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Mangle - Bear"] = {"effects for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Mangle - Cat"] = {"effects for %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Lacerate"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Lifebloom"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Maim"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Savage Roar"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Cyclone"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DRUID"]["Eclipse"] = {"buff", nil, {["live"] = 1, ["spell"] = {"Eclipse CD", 30}}};

	SPELL_TIMER_PATTERN_TABLE["SHAMAN"] = {};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["Stormstrike"] = {"Lasts %t"};
	SPELL_TIMER_PATTERN_TABLE["SHAMAN"]["Maelstrom Weapon"] = {"buff", nil, {["live"] = 1}};

	SPELL_TIMER_PATTERN_TABLE["PALADIN"] = {};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Hammer of Justice	"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Repentance"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Turn Undead"] = {"up to %t"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Divine Illumination"] = {"for %t", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Light's Grace"] = {"lasts %t", nil, {["notarget"] = 1, ["live"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Beacon of Light"] = {"buff"};
	SPELL_TIMER_PATTERN_TABLE["PALADIN"]["Righteous Vengeance"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["MAGE"] = {};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Polymorph"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Cone of Cold"] = {"for %t", {"Frostbolt"}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Frostbolt"] = {"for %t", {"Cone of Cold"}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Pyroblast"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Fireball"] = {"over %t"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Flamestrike"] = {"over %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Detect Magic"] = {"for %t"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Blast Wave"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Frost Nova"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Summon Water Elemental"] = {"for %t", nil, {["notarget"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Slow"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Living Bomb"] = {"debuff", nil, {["live"] = 1, ["unique"] = 1}};
	SPELL_TIMER_PATTERN_TABLE["MAGE"]["Improved Scorch"] = {"debuff"};

	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"] = {};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["Frost Fever"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["Blood Plague"] = {"debuff"};
	SPELL_TIMER_PATTERN_TABLE["DEATHKNIGHT"]["Ebon Plague"] = {"debuff"};
end